version: 2
jobs:
  build_web:
    docker:
      # specify the version
      - image: node:latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-web{{ checksum "package-lock.json" }}
      - run:
          name: install packages
          command: npm install
      - save_cache:
          key: dependency-cache-web{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
    
      # build and push Docker image
      - setup_remote_docker
      - run:
          name: build and push Docker image
          command: |
            curl -fsSL get.docker.com -o get-docker.sh
            sh get-docker.sh
            docker build -t hesabfun/template:latest .
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
            docker push hesabfun/template:latest

# Check https://circleci.com/docs/2.0/workflows/ for more details
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_web